# Generated by Django 5.0.7 on 2024-07-14 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tools_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
