# Generated by Django 5.0.7 on 2024-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tools_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usernname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Your_wallet_address', models.CharField(max_length=255)),
            ],
        ),
    ]
