# Generated by Django 5.0.7 on 2024-07-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Usernname',
            new_name='Username',
        ),
    ]
