# Generated by Django 5.0.7 on 2024-07-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
    ]
