# Generated by Django 5.0.7 on 2024-07-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser'),
        ('accounts', '0002_customuser_is_student_customuser_is_teacher'),
        ('accounts', '0007_remove_wallet_amount'),
    ]

    operations = [
    ]
