# Generated by Django 5.0.7 on 2024-07-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20240717_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
