# Generated by Django 5.0.7 on 2024-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
    ]
