# Generated by Django 5.0.7 on 2024-07-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_wallet_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
