# Generated by Django 5.0.7 on 2024-07-18 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_wallet_userwallet_nameofuser_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameofuser',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Your_wallet_address',
            new_name='Your_trc20_wallet_address',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='userwallet',
        ),
    ]
