# Generated by Django 5.0.7 on 2024-07-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_nameofuser_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
