# Generated by Django 5.0.7 on 2024-07-23 05:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_wallet_userprofile_delete_nameofuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userprofile',
            new_name='profile',
        ),
        migrations.DeleteModel(
            name='wallet',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='amount',
            new_name='account_detals',
        ),
    ]
