# Generated by Django 5.0.7 on 2024-07-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_userprofile_profile_delete_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
    ]
