# Generated by Django 5.0.7 on 2024-07-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_order_success'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_success',
        ),
        migrations.AddField(
            model_name='profile',
            name='msg',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
