# Generated by Django 5.0.7 on 2024-07-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_delete_order_success_profile_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(default='You dont have sufficient fund for tool yet', max_length=500),
        ),
    ]
