# Generated by Django 4.2.11 on 2024-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_profile_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200, null=True)),
            ],
        ),
    ]
