# Generated by Django 4.2.11 on 2024-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_order_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(default='You dont have sufficient fund for tool yet, fund wallet and buy a tool', max_length=500),
        ),
    ]
