# Generated by Django 4.2.11 on 2024-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_profile_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(default='You dont have sufficient fund for tool yet.', max_length=500),
        ),
    ]
