# Generated by Django 4.2.11 on 2024-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(default='You dont have sufficient fund to purchase any tool, fund wallet.', max_length=500),
        ),
    ]
