# Generated by Django 4.2.11 on 2024-07-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_tools_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Username',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Your_trc20_wallet_address',
            field=models.TextField(max_length=255),
        ),
    ]
