# Generated by Django 4.2.11 on 2024-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_contactus_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Your_trc20_wallet_address',
            field=models.CharField(max_length=255),
        ),
    ]
