# Generated by Django 4.2.11 on 2024-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_contactus_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(default='Welcome, {self.username}  fund wallet.', max_length=500),
        ),
    ]
