# Generated by Django 4.2.11 on 2024-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_profile_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg',
            field=models.TextField(default='Hello, welcome fund wallet and shop the best tools.', max_length=500),
        ),
    ]
