# Generated by Django 4.2.11 on 2024-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_profile_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Amount_Transfered',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
